source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

link_with 'UltimateUp'
target 'UltimateUp' do

pod 'FBSDKCoreKit'
# pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'GoogleMaps'
# pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift-2'
# pod 'Socket.IO-Client-Swift'

end

target 'UltimateUpTests' do

end

