# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'UltimateUp' do
# pod 'AFNetworking', '~> 2.0'
# pod 'Alamofire', '~> 1.1'
# pod 'Facebook-iOS-SDK'
# pod 'Starscream', :git => "https://github.com/daltoniam/starscream.git", :tag => "0.9.1"
end

target 'UltimateUpTests' do

end

